version: '3'

services:
  realworld.auth.db:
    image: mysql:5.7.22
    container_name: realworld.auth.db
    restart: unless-stopped
    tty: true
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: ${DB_AUTH_DATABASE}
      MYSQL_USER: ${DB_AUTH_USERNAME}
      MYSQL_PASSWORD: ${DB_AUTH_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_AUTH_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - .env
    volumes:
      - realworld-dbdata-auth:/var/lib/mysql/
      - ./etc/infrastructure/config/shared/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - realworld

  realworld.auth.app:
    build:
      context: .
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: realworld.auth.app
    restart: unless-stopped
    tty: true
    ports:
      - 8879:8879
      - 9001:9000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./etc/infrastructure/config/blog-api/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    depends_on:
      - realworld.auth.db
    command: php -S realworld.auth.app:8879 -t apps/blog-auth/public
    networks:
      - realworld

  realworld.blog.db:
    image: mysql:5.7.22
    container_name: realworld.blog.db
    restart: unless-stopped
    tty: true
    ports:
      - 3361:3306
    environment:
      MYSQL_DATABASE: ${DB_BLOG_DATABASE}
      MYSQL_USER: ${DB_BLOG_USERNAME}
      MYSQL_PASSWORD: ${DB_BLOG_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_BLOG_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - .env
    volumes:
      - realworld-dbdata-blog:/var/lib/mysql/
      - ./etc/infrastructure/config/shared/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - realworld

  realworld.blog.app:
    build:
      context: .
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: realworld.blog.app
    restart: unless-stopped
    tty: true
    ports:
      - 8880:8880
      - 9000:9000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./etc/infrastructure/config/blog-api/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    depends_on:
      - realworld.blog.db
    command: php -S realworld.blog.app:8880 -t apps/blog-api/public
    networks:
      - realworld

  realworld.phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: realworld.phpmyadmin
    ports:
      - 8881:80
    environment:
      - PMA_HOSTS=realworld.auth.db,realworld.blog.db
      - PMA_PORTS=3306,3306
    depends_on:
      - realworld.auth.db
      - realworld.blog.db
    networks:
      - realworld

  # realworld.localstack:
  #   container_name: realworld.localstack
  #   image: localstack/localstack-full:latest
  #   environment:
  #     - SERVICES=s3,sqs,sns
  #     - DEBUG=1
  #     - DEFAULT_REGION=eu-west-1
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #     - LOCALSTACK_LOCAL_BUCKET=realworld-local
  #     - LOCALSTACK_HOSTNAME=realworld-localstack
  #     - DATA_DIR=/tmp/localstack-bucket
  #     - LAMBDA_EXECUTOR=docker
  #     - START_WEB=1
  #     - PORT_WEB_UI=8099
  #   ports:
  #     - 44566:4566 # S3
  #     - 8099:8080
  #   volumes:
  #     - './etc/localstack/init:/docker-entrypoint-initaws.d' # initialize scripts
  #     - './etc/localstack/.keys:/tmp/localstack' # private & public keys for auth
  #     - './etc/localstack/bucket:/tmp/localstack-bucket' # data to load in bucket, pushed by init script

networks:
  realworld:
    driver: bridge

volumes:
  realworld-dbdata-auth:
    driver: local
  realworld-dbdata-blog:
    driver: local
