###
# 1 Authentication
POST localhost:8880/api/users/login
Content-Type: application/json

{
    "user": {
        "email": "jake@jake.jake",
        "password": "jakejake"
    }
}

###
# 2 Registration
POST localhost:8880/api/users
Content-Type: application/json;

{
    "user": {
        "email": "jake@jake.jake",
        "username": "Jacob",
        "password": "jakejake"
    }
}

###
# 3 Get current user
GET localhost:8880/api/user
Content-Type: application/json;

###
# 4 Update user
PUT localhost:8880/api/user
Content-Type: application/json;

{
    "user":{
        "email": "jake@jake.jake",
        "bio": "I like to skateboard",
        "image": "https://i.stack.imgur.com/xHWG8.jpg"
    }
}
